src/TeamManagement/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using TeamManagement.Entity;
using TeamManagement.Models;
using TeamManagement.Services;

namespace TeamManagement.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IWebHostEnvironment _hosting;

       

        public EmployeeController(IEmployeeService employeeService, IWebHostEnvironment hosting)
        {
            _employeeService = employeeService;
            _hosting = hosting;
        }
        [HttpGet]
        [HttpPost]
        public IActionResult Index(string empNo, string sortOrder)
        {
            ViewData["EmployeeNoSort"] = string.IsNullOrEmpty(sortOrder) ? "Emp_No" : "";
            ViewData["NameSort"] = sortOrder == "Name_Asc_Sort" ? "Name_Desc_Sort" : "Name_Asc_Sort";

            List<EmployeeIndexViewModel> employees;
            if(string.IsNullOrEmpty(empNo))
            {
                 employees = _employeeService.GetAllEmployees(empNo).Select(employee => new EmployeeIndexViewModel
                {
                    Id = employee.Id,
                    EmployeeNo = employee.EmployeeNo,
                    FullName = employee.FullName,
                    ImageUrl = employee.ImageUrl
                }).ToList();
                switch(sortOrder)
                {
                    case "Emp_No":
                        employees = employees.OrderByDescending(e => e.EmployeeNo).ToList();
                        break;
                    case "Name_Asc_Sort":
                        employees = employees.OrderBy(e => e.FullName).ToList();
                        break;
                    case "Name_Desc_Sort":
                        employees = employees.OrderByDescending(e => e.FullName).ToList();
                        break;
                    default:
                        employees = employees.OrderBy(e => e.EmployeeNo).ToList();
                        break;
                }
                return View(employees);
            }
            else
            {
                employees = _employeeService.GetAllEmployees(empNo).Select(employee => new EmployeeIndexViewModel
                {
                    Id = employee.Id,
                    EmployeeNo = employee.EmployeeNo,
                    FullName = employee.FullName,
                    ImageUrl = employee.ImageUrl
                }).ToList();
                return View(employees);
            }

            
        }

        [HttpGet]
        public IActionResult Create()
        {
            var managers = _employeeService.GetManagers();
            ViewBag.Managers = managers.Select(x => new SelectListItem { Value = x, Text = x });
            var model = new EmployeeCreateViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeCreateViewModel model)
        {
            if(ModelState.IsValid)
            {

                var employee = new Employee
                {
                    Id = model.Id,
                    EmployeeNo = model.EmployeeNo,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    MiddleName = model.MiddleName,
                    FullName = model.FullName,
                    Email = model.Email,
                    PreferredContactNumber = model.PreferredContactNumber,
                    EmploymentStatus = model.EmploymentStatus,
                    Position = model.Position,
                    Department = model.Department,
                    StartDate = model.StartDate,
                    Shift = model.Shift,
                    FavouriteColor = model.FavouriteColor,
                    Address = model.Address,
                    City = model.City,
                    PostCode = model.PostCode,
                    Role= model.Role
                };
                if(model.ImageUrl != null && model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/employee";
                    var fileName = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webRootPath = _hosting.WebRootPath;
                    fileName = DateTime.UtcNow.ToString("yyyymmssfff") + fileName + extension;
                    var path = Path.Combine(webRootPath, uploadDir, fileName);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    employee.ImageUrl = "/" + uploadDir + "/" + fileName;
                }
                await _employeeService.AddEmployee(employee);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var employee = _employeeService.GetById(id);
            var managers = _employeeService.GetManagers();
            ViewBag.Managers = managers.Select(x=> new SelectListItem {Value = x, Text= x });
            if(employee == null)
            {
                return NotFound();
            }
            var model = new EmployeeUpdateViewModel()
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                MiddleName = employee.MiddleName,
                Email = employee.Email,
                PreferredContactNumber = employee.PreferredContactNumber,
                EmploymentStatus = employee.EmploymentStatus,
                Position = employee.Position,
                Department = employee.Department,
                StartDate = employee.StartDate,
                EndDate = employee.EndDate,
                Shift = employee.Shift,
                FavouriteColor = employee.FavouriteColor,
                Address = employee.Address,
                City = employee.City,
                PostCode = employee.PostCode,
                Role = employee.Role,
                ManagerId = employee.ManagerId
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeUpdateViewModel model)
        {
            if(ModelState.IsValid)
            {
                var employee = _employeeService.GetById(model.Id);
                var current = JsonConvert.DeserializeObject<Employee>(JsonConvert.SerializeObject(employee));
                
                if (employee == null)
                {
                    return NotFound();
                }
                employee.EmployeeNo = model.EmployeeNo;
                employee.FirstName = model.FirstName;
                employee.MiddleName = model.MiddleName;
                employee.LastName = model.LastName;
                employee.Email = model.Email;
                employee.PreferredContactNumber = model.PreferredContactNumber;
                employee.EmploymentStatus = model.EmploymentStatus;
                employee.Position = model.Position;
                employee.Department = model.Department;
                employee.StartDate = model.StartDate;
                employee.EndDate = model.EndDate;
                employee.Shift = model.Shift;
                employee.FavouriteColor = model.FavouriteColor;
                employee.Address = model.Address;
                employee.City = model.City;
                employee.PostCode = model.PostCode;
                employee.ManagerId = model.ManagerId;
                employee.Role = model.Role;
                if(model.ImageUrl != null && model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/employee";
                    var fileName = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webRootPath = _hosting.WebRootPath;
                    fileName = DateTime.UtcNow.ToString("yyyymmssfff") + fileName + extension;
                    var path = Path.Combine(webRootPath, uploadDir, fileName);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    employee.ImageUrl = "/" + uploadDir + "/" + fileName;
                }
                await _employeeService.UpdateEmployee(employee);
                await _employeeService.TrackChanges(current, employee);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpGet]
        public IActionResult Detail(int id)
        {
            var employee = _employeeService.GetById(id);
            if(employee == null)
            {
                return NotFound();
            }
            EmployeeDetailViewModel model = new EmployeeDetailViewModel()
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                FullName = employee.FullName,
                ImageUrl = employee.ImageUrl,
                Email = employee.Email,
                PreferredContactNumber = employee.PreferredContactNumber,
                EmploymentStatus = employee.EmploymentStatus,
                Position = employee.Position,
                Department = employee.Department,
                Shift = employee.Shift,
                StartDate = employee.StartDate,
                EndDate = employee.EndDate,
                FavouriteColor = employee.FavouriteColor,
                Address = employee.Address,

src/TeamManagement/Controllers/ReportsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TeamManagement.Models;
using TeamManagement.Services;

namespace TeamManagement.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IWebHostEnvironment _hosting;

        public ReportsController(IEmployeeService employeeService, IWebHostEnvironment hosting)
        {
            _employeeService = employeeService;
            _hosting = hosting;
        }

        [HttpGet]
        public IActionResult Permissions()
        {
            var employees = _employeeService.GetPermissions().Select(employee => new EmployeeRoleViewModel
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                Name = employee.FullName,
                Role = employee.Role
            }).ToList();

            return View(employees);

        }

        [HttpGet]
        public IActionResult Weekly()
        {

            var employeeDates = _employeeService.GetAllEmployees()
                .Select(x=> new { HireDate = StartOfWeek(x.StartDate, DayOfWeek.Monday) })
                .GroupBy(y=>y.HireDate).Select(z=>new { HireWeek = z.Key, HireCount = z.Count() }).ToList();

            var last24Weeks = new List<DateTime>();
            var now = DateTime.Now;
            for (int i = 0; i < 24; i++)
            {
                last24Weeks.Add(StartOfWeek(now.AddDays(-7 * i), DayOfWeek.Monday));
            }
            var weeks = last24Weeks.Select(x => new { WeekDate = x });
            var finalData = from week in weeks
                            join empWeeks in employeeDates on week.WeekDate equals empWeeks.HireWeek into gj
                            from subweek in gj.DefaultIfEmpty()
                            select new WeeklyHiresViewModel { WeekStartDate = week.WeekDate, HiredNumber = subweek?.HireCount ?? 0 };

            return View(finalData);

        }


        [HttpGet]
        public IActionResult Terminated()
        {
            var employees = _employeeService.GetTerminatedEmployees()
                .GroupBy(x => x.EndDate.Year)
                .Select(y => new TerminatedEmployeesViewModel() { TerminatedYear = y.Key, Total = y.Count() });

            return View(employees);

        }


        [HttpGet]
        [HttpPost]
        public IActionResult ActivityReport(string empNo = null)
        {
            IEnumerable<ActivityDetailsViewModel> data = new List<ActivityDetailsViewModel>();
            if (empNo == null)
            {
                data = _employeeService.GetActivities()
                    .OrderByDescending(x => x.ModifiedDateTime)
                    .Select(y => new ActivityDetailsViewModel()
                    {
                        EmployeeNo = y.EmployeeNo,
                        PropertyName = y.PropertyName,
                        PreviousValue = y.PreviousValue,
                        NewValue = y.NewValue,
                        ModifiedDateTime = y.ModifiedDateTime
                    }); ;
            }
            else
            {
                data = _employeeService.GetActivities()
                    .Where(x => x.EmployeeNo.IndexOf(empNo) >= 0)
                    .OrderByDescending(x => x.ModifiedDateTime)
                    .Select(y=>new ActivityDetailsViewModel()
                    {
                        EmployeeNo = y.EmployeeNo,
                        PropertyName = y.PropertyName,
                        PreviousValue = y.PreviousValue,
                        NewValue = y.NewValue,
                        ModifiedDateTime = y.ModifiedDateTime
                    });
            }
            ViewData["empNo"] = empNo;

            return View(data);

        }


        private static DateTime StartOfWeek(DateTime dt, DayOfWeek startOfWeek)
        {
            int diff = (7 + (dt.DayOfWeek - startOfWeek)) % 7;
            return dt.AddDays(-1 * diff).Date;
        }
    }
}

src/TeamManagement/Views/Reports/ActivityReport.cshtml
@model IEnumerable<ActivityDetailsViewModel>

@{ ViewBag.Title = "Activity Details";}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Update Activity Report</li>
                    </ol>
                </nav> <br /><br />
                <div class="row">
                    <div class="col-md-12 table-responsive-md">
                        <form asp-controller="Reports" asp-action="ActivityReport">
                            <p>
                                <input type="text" name="empNo" />
                                <input type="submit" value="Search" />

                            </p>
                        </form>
                        @if (@ViewData["empNo"] != null)
                        {
                    <h4>You searched for employee @ViewData["empNo"] </h4>
                        }
                       

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Employee No</th>
                                    <th>Property Name</th>
                                    <th>Previous Value</th>
                                    <th>New Value</th>
                                    <th>ModifiedDate</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>@item.EmployeeNo</td>
                                        <td>@item.PropertyName</td>
                                        <td>@item.PreviousValue</td>
                                        <td>@item.NewValue</td>
                                        <td>@item.ModifiedDateTime</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/TeamManagement/Views/Reports/Permissions.cshtml
@model IEnumerable<EmployeeRoleViewModel >

@{ ViewBag.Title = "Reports";}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Employee Permissions List</li>
                    </ol>
                </nav> <br /><br />
                <div class="row">
                    <div class="col-md-12 table-responsive-md">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Employee No.</th>
                                    <th>Name</th>
                                    <th>Role</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            <a asp-controller="Employee" asp-action="Detail" asp-route-id="@item.Id">
                                                @item.EmployeeNo
                                            </a>
                                        </td>
                                        <td>@item.Name</td>
                                        <td>
                                            @item.Role
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/TeamManagement/Views/Reports/Terminated.cshtml
@model IEnumerable<TerminatedEmployeesViewModel>

@{ ViewBag.Title = "Terminated Employees Report";}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Terminated Emplopyess Report</li>
                    </ol>
                </nav> <br /><br />
                <div class="row">
                    <div class="col-md-12 table-responsive-md">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Terminated Year</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>@item.TerminatedYear</td>
                                        <td>
                                            @item.Total
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

src/TeamManagement/Views/Reports/Weekly.cshtml
@model IEnumerable<WeeklyHiresViewModel>

@{ ViewBag.Title = "Weekly Hired Report";}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item active" aria-current="page">Weekly Hired Emplopyess Report</li>
                    </ol>
                </nav> <br /><br />
                <div class="row">
                    <div class="col-md-12 table-responsive-md">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Week Start Date</th>
                                    <th>Employees Hired</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>

                                        <td>@item.WeekStartDate.ToShortDateString()</td>
                                        <td>
                                            @item.HiredNumber
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>